version: '2'

services:
    postgres:
        image: postgres:9.6
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ./.data/pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    php:
        build: docker/php7-fpm
        env_file: ./.env
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        links:
            - postgres
    nginx:
        build: docker/nginx
        ports:
            - ${WEB_PORT}:80
        volumes_from:
            - php
        volumes:
            - ${LOGS_DIR}/nginx/:/var/log/nginx
    node:
        build: docker/node
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        command: bash -c "yarn install && yarn watch"
    pgadmin:
        image: dpage/pgadmin4:latest
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
            PGADMIN_DEFAULT_PASSWORD: pgadmin
        volumes:
            - /data/pgadmin:/root/.pgadmin
        ports:
            - "5050:80"
        restart: always
        restart: unless-stopped